### ISSUE TITLE
Difference between both the filterlists?

### ISSUE THREAD

**Issue by Rtizer-9** [kowith337/PersonalFilterListCollection#25]
Hey there, I just came to know about your filterlists through filterlists.com and found that they are extremely good at what they claim to be.

I'm currently using both of your facebook lists (on desktop) (only zuckestion and xfiles on android) but unable to understand what that module list actually does.

Also can you please give suggestions about the best setup a person should have to make the best use of your lists.
My current setup is faceslim (touch.facebook.com selected + adguard's latest nightly which have out of box support for custom filterlists among other amazing options.

I'm unable to block ads in faceslim with this setup right now. (I know that your lists are more focused on firefox on android but you know its more convenient to just open a single app).

I'll grateful if you can describe about the above things in detail.

I also want you to know that xfiles noads list blocked one request which your list didn't blocked (the line which blocked it is the 2nd line which comes when you search for 'substream' in the xfiles noads list). I'm not an expert so I don't know whether or not it needs to be added in your lists right now so take your time to decide what needs to be done about that.

I'm extremely happy that such a lists exists and can actually see the list blocking several requests in the adguard filter log which other main filters like adguard base filter and now added easylist or easyprivacy doesn't block by default.

Thanks :)

**Comment by kowith337** [comment]
I'm lack of support AdGuard filters because I didn't have that tools (and not paid for the app yet), also some filtering rules are different than uBlock Origin, that cause some rules cannot be apply on other programs.

Keep in mind the list is based on my Facebook usage experience, I guess I won't see any ads for a long time after dealing with ads interests (by remove, block and delete them all, no matter what), and you know Facebook will update their sites and may serve the different site versions to keep their ads survived from any blocking attempts, like it's happen to me after I've create some rules in my filters to testing before pushing in the repo, but unfortunately, the blocked elements was survived after refresh page because the sites will scramble the DOM `id` and `class` to bypass any blocking attempts...

The different between modules command lists and zuckestion killer is...

### Modules command list
- This probably focused to desktop sites (by design)
- Only block specific connections that have `?modules=WhatFunctionShouldBeBlocked`
- All module commands are likely start with `/ajax/haste-response/?modules=` that you can observe those connections on desktop site, e.g.
  - blocking `PubcontentFeedChainingControllerX` connections will prevent Facebook show related articles under a post that linked to external sites.

### Zuckestion Killer
- Do both things, to hide unwanted elements (DOM) and prevent unwanted connections
- Will be aggressively against `Free Basics` services and subdomains that targeted to mobile data users and carrier who participate with Facebook to allow `Free Basics` available for their customers. (details given at #9 and [this guide](https://github.com/kowith337/PersonalFilterListCollection/blob/master/docs/Facebook0-Bypassing.md))

**Comment by Rtizer-9** [comment]
So I guess I can keep using both of them on desktop and Zuckestion on android. Right?

I do understand facebook will keep finding ways to push their ads down our throat however hard we try.

As I asked before, what according to you, is the best way to supplement your list in terms of the exact app to open facebook, user agent etc. to minimise the number of ads and tracking connections and layout and speed (if that's even possible).

This is the main question I want to ask you.

I'm currently using faceslim with touch.facebook.com option and  a custom user agent I found on some website which has surprisingly brought down the number of ads to just 1-2.

You can try the adguard trial version for 7 days IIRC. Also you can talk to their respective developers if you want help in making your list more aggressive and useful coz I really find your list to be irreplaceable.

**Comment by Rtizer-9** [comment]
Hey there again.

As I can see you're a non native speaker, I want to clarify that in case its not clear I've asked a question in previous comment which I'm eagerly waiting for you to answer.

If you're going to answer it later its completely ok, I just wanted to clarify that my one question is still unanswered.

**Comment by kowith337** [comment]
OK, I'll try again...

> can you please give suggestions about the best setup a person should have to make the best use of your lists.

There aren't have an alternative way to use other things than Firefox for Android (or [other forks](https://github.com/kowith337/ThaiParanoidBlock/wiki/Other-Firefox-based-browser)) + uBlock Origin extension for now, sorry.

> I'm unable to block ads in faceslim with this setup right now. (I know that your lists are more focused on firefox on android but you know its more convenient to just open a single app).

Same as above, however, I will try to convert for compatibility, if I can do...

> I also want you to know that xfiles noads list blocked one request which your list didn't blocked (the line which blocked it is the 2nd line which comes when you search for 'substream' in the xfiles noads list). I'm not an expert so I don't know whether or not it needs to be added in your lists right now so take your time to decide what needs to be done about that.

Did you mean DOM element name?
https://github.com/gioxx/xfiles/blob/26719e10cd2b63b7300a7d14ca6e7cc354578927/facebook.txt#L64

I didn't add any DOM ID wildcard that start with `substream_`, I guess it's maybe handled by `div[id^="hyperfeed_story_id]"`, I have no idea is some desktop news feed ads doesn't have the `hyperfeed_story_id` in the beginning of DOM ID and post ads bypassed as a result?

**Comment by Rtizer-9** [comment]
Thanks for replying.

I specifically wanted answer for the first question.

As I said before I'm not an expert so I don't know if that substream filter is necessary or not. Although I want to tell you that its line 63 and not 64.
