### ISSUE TITLE
Gelbooru with GelboLube looks slightly wrong

### ISSUE THREAD

**Issue by Jorge9811** [kowith337/PersonalFilterListCollection#46]
### Describe the issue
The page content looks slightly wrong

### Steps to reproduce
1. Go to Gelbooru
2. Search anything on the search bar
3. 
4. 
...

### Expected behaviour
Slim bar with options of the same size as the blue one

### Actual behaviour
Bigger bar than the blue one

### Screenshots
![untitled](https://user-images.githubusercontent.com/54429803/66744705-7c807380-ee53-11e9-9ab3-569ecb1e5fc8.png)

### Additional notes

I'm using Mozilla Firefox 69.0.3 and these are the filters I'm using on uBlock
![1](https://user-images.githubusercontent.com/54429803/66744854-e39e2800-ee53-11e9-9dbc-1ccadeca637a.png)
![2](https://user-images.githubusercontent.com/54429803/66744856-e39e2800-ee53-11e9-8ec4-f7fab1ef85a6.png)

If more info is needed lmk

**Comment by kowith337** [comment]
It seems like extra menu were added (The `Supporters` are added in) and due to the size is overflowing and cannot fit the content anymore

I'm also see the `R18` ads are re-appearing, I will also looking for it.

**Comment by kowith337** [comment]
- All menu are strictly apply normal font weight and reduce padding to 4 pixels for each side.
- All menu that highlighted with `<b>` tag are set font weight to normal now, and disabled padding for highlighted menu items to prevent additional padding (`a 4 + b 0` not `a 4 + b 4`)

**Comment by Jorge9811** [comment]
Almost everything seems to be working now. The only single issue left is that when you type in a part of a tag inside a post _(like for example typing in "aud" in the search bar to complete "audio" while you're watching a webm or a pic)_, the list of tags doesn't show up. It only shows up during a search.
https://streamable.com/pyvrg

Other than that, everything seems to be working perfectly now. Thanks!

**Comment by kowith337** [comment]
https://github.com/kowith337/PersonalFilterListCollection/blob/477e59c8e7b522c8ad299bbac6641d7b5f7b7852/filterlist/imageboard/GelboLube.txt#L230

Because I've blocked every `*.php` requests that not match these request type.

- `document`, where you can view their sites.
- `inline-script`, to allow script inside current document to be execute.
- `xmlhttprequest`, previously, all **AutoComplete** are rely to that, but not anymore because it's switched to `beacon` instead.

Furthermore, they often use `*.php` requests for abusive way to make sure blocked ads can be survive or bypass, and I'm aware that allow `beacon` for `*.php` may be leak ads code to be re-execute.
