### ISSUE TITLE
mobilenetworkscoring-pa.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#50]
### What type of resource that you're use?
FilterList

### Describe the issue
mobilenetworkscoring-pa.googleapis.com is being blocked
It is required by some Android apps. It is used to check connectivity. WIthout it, I have noticed some apps not pushing notifications.

**Comment by kowith337** [comment]
Prefer that it's a problem from my hosts file, from my leftover hosts, right?

I'm aware that the main purpose of it's domain is use for receive information about how good of nearby network (Wi-Fi) and/or your mobile connections (Cellular data), and may submitting measured data back to home server. (I cannot confirm about this, either, but blocked by self-concern.)

I don't really have any idea that some apps really require that, the related things that likely similar is blocking `connectivitycheck.gstatic.com` will prevent _Google Play Store_ update any apps because pinging to that domain for check connections is never be done and _Play Store_ will be thing that you're still not connected to internet properly.
> It's not mainly my problem, unless some apps are really need to install from _Play Store_, otherwise it will show annoyance sticky notification for telling that **you need to install it's apps from Play Store only and/or properly.**

What apps you've setup to block hosts and/or domains, blokada, DNSFilter, DNS66 or something else?
I may temporary whitelist that, but I will still apply to other place, such as pDNSF additional blocklist and my combined hosts file.

**Comment by p1r473** [comment]
It was either the Canary or Kijiji app
I am assuming it didn't push push notifications if it thinks maybe there is weak wifi.
I am using Pihole project to test this. I did whitelist it and it had fixed the issue.

**Comment by kowith337** [comment]
I probably revert next if it's not really matter to allow, since I've switched from Android 5.

But based on your feedback, I may cancel that process...

**Comment by p1r473** [comment]
Seems to be still blocked, not sure if this is on purpose @kowith337

**Comment by kowith337** [comment]
Again, what's the to point to allow such its behaviour to determine mobile network quality for just play the game or use the app that rely to it.

**Please blame developers of those apps, not myself!**
