### ISSUE TITLE
instantmessaging-pa.googleapis.com breaks Google Messages for Web

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#52]
### What type of resource that you're use?
Hosts file

### Describe the issue
instantmessaging-pa.googleapis.com breaks Google Messages for Web

### Steps to reproduce
1. try to visit  messages.google.com/web/
2.  QR code doesn't show up

### Expected behaviour
QR code shows up

### Actual behaviour
QR code doesn't show up

### Screenshots
![image](https://user-images.githubusercontent.com/9235633/77182751-a04f8180-6aa3-11ea-87e0-e2ed5bc1986e.png)

**Comment by kowith337** [comment]
I'm sorry but what the main purpose for request me to whitelist?
- Did you really read my little description inside my hosts file?
- Are your tools that you've setup (pi-hole) cannot set to whitelist by your side instead of mine?
- Can I counter some?

First, as I can tell, I rarely and may never use that feature!

Second, I'm observed log from pDNSF app and then added that, but didn't know it's purpose for that moment, however, it's clearly that domain are related to your issue, by pair the phone through QR code for viewing messages in phone (SMS, MMS)

Yet again, if the feature can be use on demand, why I see many attempts in Android phone to pinging to that domain, even I didn't use that feature?

**Comment by p1r473** [comment]
Yes, I can whitelist on my end
Opened this ticket just in case you choose to whitelist on your end as well
If you do not whitelist on your end, no problem
(Anyone else who uses your list may be impacted too)

**Comment by p1r473** [comment]
This seems to be still blocked even though you have whitelisted

**Comment by kowith337** [comment]
I've already tell enough that if users really want to use that feature, `Google` must fix its app to connect only when users really want to use, not periodically attempt connect if users didn't use it!
As I remember, I've moved into aggressive list, that's mean again, it's problem by your side of...
- caching my blocklist and may not purge and/or update.
- subscribe my lists from other place that may merged my lists but didn't update frequently enough.
- or you're also subscribe both generic leftover and aggressive list altogether.
if you subscribe to aggressive list, it's mean now it's personal issue, and I cannot fix your problem anymore.
