### ISSUE TITLE
telephonyspamprotect-pa.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#55]
Hi,
Blocking this domain breaks Google Messenger's fraud/spam detection feature.
I have whitelisted on my end but you might want to remove.

**Comment by kowith337** [comment]
It your choice if you trust its company enough, but my choice is "No send and either receive"
- This host may corresponding with `dialercallinfolookup-pa.googleapis.com` that submit numbers for analysis, but can I trust that they won't use for other purpose than **Scanning** because it's upload all of numbers you've receive and call out!
- I've already said that if somebody touching phone numbers, it's mean they want to collect them, you may see `Facebook` reputation is gone down by that!
