### ISSUE TITLE
GoogleAD&ID

### ISSUE THREAD

**Issue by e-tw** [kowith337/PersonalFilterListCollection#63]
### What type of resource that you're use?

Google AdService and ID.Google tracking hostsz

### Describe the issue

Hope to add content.
Could you please convert and output a copy to ABP format?
Thank you.

### Expected behaviour

0.0.0.0 id.google.tw
0.0.0.0 adservice.google.tw

**Comment by kowith337** [comment]
Sorry, I have no plan to support ABP, even though I can convert to ABP format, but i'm not sure the default exclusion list (aka. whitelist) of that add-ons are allowed those domains or not.

I understand that anybody who use ABP can opt-out to deny default exclusion list, but unlike uBO that we can counter any excluded rules with `$important` flag.

Maybe just in case, I will to do this anyway because the `[AdBlock Plus]` header identifier can readable in AdGuard, but doesn't mean I'm actually use or doing this for recommendation the tools, only just for compatible.

**Comment by e-tw** [comment]
OK,Then please add the two above first.

Can you join the two below?
0.0.0.0 googletagmanager.com
0.0.0.0 google-analytics.com

**Comment by kowith337** [comment]
> 0.0.0.0 googletagmanager.com
> 0.0.0.0 google-analytics.com

Hmm, I cannot guaranteed for blocking these after recreate as ABP format, some common and default filterlists may allow those domains for unbreak site (it's still shady to allow, so...)

**Comment by e-tw** [comment]
OK,No problem at the moment.

**Comment by llacb47** [comment]
for abp/ubo you can use `||adservice.google.*^`
