### ISSUE TITLE
firebaseremoteconfig.googleapis.com reminders-pa.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#64]
Hi,
Currently, blocking firebaseremoteconfig.googleapis.com and reminders-pa.googleapis.com

Reminders is a domain for the Google Home reminders app
Firebase Remote Config is a cloud service that lets you change the behaviour and appearance of your app without requiring users to download an app update. 

Neither are malicious nor advertising.

Thanks

**Comment by kowith337** [comment]
I have none of apps and any of `Google`-tracked IoT hardware, also I have no plan to buy and use them.

However, I'm still see pDNSF logged and blocked that domains too often, I think it's maybe use by other apps or used by GMS itself (because I've disabled some `Google` apps, include its main one), and
it's already in aggressive list, so nothing to do.

Also, any apps that still relying to connect `Firebase` are treated by myself that suspicious because contacting to some `Firebase` servers is mean the app isn't privacy-friendly.

**Note for you...**

1. You're often delete every texts from templates, I will treated as low-priority or ignore in the future.
2. you didn't check that some hosts still in the aggressive list, any hosts that listed in will be not removed out, no matter what.
3. In case if it's match the two conditions above, I will enforce lockdown issues instead.

**Comment by p1r473** [comment]
Thanks, will check template and aggressive list before posting
