### ISSUE TITLE
b-api.facebook.com b-graph.facebook.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#65]
### What type of resource that you're use?
PiHole

### Describe the issue
Blocking these domain breaks logging into Facebook Messenger on mobile.

### Steps to reproduce
1.  Block b-api.facebook.com b-graph.facebook.com
2. Try to log into Facebook Messenger on mobile

### Expected behaviour
I can log into Facebook Messenger

### Actual behaviour
Facebook Messenger gives error "check your internet connection"

### Screenshots

![image](https://user-images.githubusercontent.com/9235633/94500181-a948aa80-01cc-11eb-9617-8ee10e470d3c.png)

### Logs
Sep 28 00:25:15 dnsmasq[2682]: query[A] b-api.facebook.com from 192.168.1.111
Sep 28 00:57:00 dnsmasq[2682]: query[A] b-graph.facebook.com from 192.168.1.111

**Comment by kowith337** [comment]
I can't denied that blocking the `b-api` and `b-graph` will be occur the login attempt because I didn't mainly have any interests to use any official apps from `Facebook`, except `Messenger Lite` that doesn't having extra features (Stories, Games, etc.) and (maybe) advertisements that appear in the chat list, another reason is Facebook somehow wants to redirect to `z-*` (aka. `Free Basics`) servers when connectiong from mobile data that also have Free (by trading our privacy and tracking your phone numbers regardless of already giving to them or not) services available in that carrier, such as `Free Basics`, `Discover`, `ExpressWiFi`

However, I think I've moved into aggressive list already, so I have nothing to do for now...
