### ISSUE TITLE
Facebook blocking seems to be broken by removing every feed item

### ISSUE THREAD

**Issue by Thraka** [kowith337/PersonalFilterListCollection#69]
### What type of resource that you're use?
Filterlist

### Describe the issue
I imported the raw version of https://github.com/kowith337/PersonalFilterListCollection/blob/master/filterlist/facebook/FacebookZuckestionKiller.txt and I noticed today (I don't use facebook too often but I think I did a week or two ago without issue) that it's purging every post in the feed automatically.

### Steps to reproduce
1. Open facebook to the main site

### Expected behaviour
Only block the bad posts.

### Actual behaviour
Removes every post.

### Screenshots
N/A

### Logs
I can't seem to grab logs. Because the issue removes the top X posts, the site loads the next X posts, which then then are removed and cycle repeats indefinitely. 

### Additional notes
N/A

**Comment by kowith337** [comment]
I cannot reproduce with my account for now, however, some of posts maybe probably hidden by this rule...
`facebook.com##div[role="feed"]> div[data-pagelet^="FeedUnit"] div > span > span > a > span:upward(div[data-pagelet^="FeedUnit"])`

For now, due to very outdated of global rules that aim for desktop site version, I will move the global rules to another files until I have more times for rework for it!

**Comment by Thraka** [comment]
That fixed my problem! Thank you!
